apiVersion: v1
kind: Pod
metadata:
  name: nginx-paris
  namespace: mon-namespace
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: zone
            operator: In
            values:
            - paris
  containers:
  - name: nginx
    image: nginx:1.29.4
